# This is a basic workflow to help you get started with Actions

name: Deploy to Elastic Beanstalk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #(remove the pound-sign and everything in parntheses to allow this to work)workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # This is required for GitHub's OIDC authentication
      contents: read    # This gives read access to the repository’s content

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # Role you created in AWS IAM
          aws-region: ${{ secrets.AWS_REGION }}  # Set the AWS region for your Elastic Beanstalk environment

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          pip install awsebcli  # Install the Elastic Beanstalk CLI (needed for deployment)

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p python-3.13 test_Env --region us-east-1  # Initialize EB CLI with your app name and region
          eb deploy  # Deploy your application to Elastic Beanstalk
